### ISSUE TITLE
another crash on axlegears's server for you

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/gregtechextras#2]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/20/15 9:51 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
    at bloodasp.gregtechextras.armor.ModularArmor_Item.getArmorTexture(ModularArmor_Item.java:394)
    at net.minecraftforge.client.ForgeHooksClient.getArmorTexture(ForgeHooksClient.java:80)
    at jds.bibliocraft.rendering.TileEntityArmorStandRenderer.func_147500_a(TileEntityArmorStandRenderer.java:129)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at bloodasp.gregtechextras.armor.ModularArmor_Item.getArmorTexture(ModularArmor_Item.java:394)
    at net.minecraftforge.client.ForgeHooksClient.getArmorTexture(ForgeHooksClient.java:80)
    at jds.bibliocraft.rendering.TileEntityArmorStandRenderer.func_147500_a(TileEntityArmorStandRenderer.java:129)

-- Block Entity Details --
Details:
    Name: ArmorStandTile // jds.bibliocraft.tileentities.TileEntityArmorStand
    Block type: ID #191 (tile.BiblioArmorStand // jds.bibliocraft.blocks.BlockArmorStand)
    Block data value: 3 / 0x3 / 0b0011
    Block location: World: (1294,69,-168), Chunk: (at 14,4,8 in 80,-11; contains blocks 1280,0,-176 to 1295,255,-161), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
    Actual block type: ID #191 (tile.BiblioArmorStand // jds.bibliocraft.blocks.BlockArmorStand)
    Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Bear989Sr'/228672, l='MpServer', x=1291.89, y=70.62, z=-165.63]]
    Chunk stats: MultiplayerChunkCache: 49, 49
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-131,64,44), Chunk: (at 13,4,12 in -9,2; contains blocks -144,0,32 to -129,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 178577448 game time, 188552632 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 24 total; [EntityCow['Cow'/228675, l='MpServer', x=1292.84, y=68.00, z=-190.44], EntityCow['Cow'/228674, l='MpServer', x=1288.47, y=68.00, z=-191.66], EntityCow['Cow'/228673, l='MpServer', x=1291.88, y=68.00, z=-191.59], EntityCow['Cow'/228679, l='MpServer', x=1283.50, y=68.00, z=-192.84], EntityCow['Cow'/228678, l='MpServer', x=1292.53, y=68.00, z=-192.84], EntityWolf['Wolf'/228677, l='MpServer', x=1307.91, y=69.00, z=-180.00], EntityBlock['unknown'/550, l='MpServer', x=1315.25, y=62.00, z=-130.75], EntityHorse['Horse'/228676, l='MpServer', x=1285.25, y=68.00, z=-190.53], EntityClientPlayerMP['Bear989Sr'/228672, l='MpServer', x=1291.89, y=70.62, z=-165.63], EntityCow['Cow'/228681, l='MpServer', x=1286.50, y=68.00, z=-192.84], EntityCow['Cow'/228680, l='MpServer', x=1289.53, y=68.00, z=-192.84], EntityTFNagaSegment['unknown'/115, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/116, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/117, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/118, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/119, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/120, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/121, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/122, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/123, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityLavaMonster['Lava Monster'/228824, l='MpServer', x=1312.50, y=10.44, z=-156.50], EntityTFNagaSegment['unknown'/124, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/125, l='MpServer', x=0.60, y=-16.80, z=0.60], EntityTFNagaSegment['unknown'/126, l='MpServer', x=0.60, y=-16.80, z=0.60]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 409164864 bytes (390 MB) / 1578631168 bytes (1505 MB) up to 1631584256 bytes (1556 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1750M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 53 mods loaded, 53 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJA  CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJA  ivtoolkit{1.2} [IvToolkit](minecraft.jar) 
    UCHIJA  MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJA  psychedelicraftcore{1.4} [Psychedelicraft Core](minecraft.jar) 
    UCHIJA  BiblioCraft{1.10.4} [BiblioCraft](BiblioCraft[v1.10.4][MC1.7.10].jar) 
    UCHIJA  gregapi{GT6-MC1710} [Greg-API](gregtech_1.7.10-6.00.50.jar) 
    UCHIJA  IC2{2.2.756-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.756-experimental.jar) 
    UCHIJA  BuildCraft|Core{7.0.19} [BuildCraft](buildcraft-7.0.19.jar) 
    UCHIJA  Forestry{3.5.7.16} [Forestry for Minecraft](forestry_1.7.10-3.5.7.16.jar) 
    UCHIJA  BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) 
    UCHIJA  BuildCraft|Silicon{7.0.19} [BC Silicon](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Transport{7.0.19} [BC Transport](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Builders{7.0.19} [BC Builders](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Robotics{7.0.19} [BC Robotics](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Energy{7.0.19} [BC Energy](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Factory{7.0.19} [BC Factory](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Compat{7.0.8} [BuildCraft Compat](buildcraft-compat-7.0.8.jar) 
    UCHIJA  CarpentersBlocks{3.3.7 DEV} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 DEV - MC 1.7.10.jar) 
    UCHIJA  Railcraft{9.6.1.0} [Railcraft](Railcraft_1.7.10-9.6.1.0.jar) 
    UCHIJA  TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJA  chisel{2.3.10.37} [Chisel 2](Chisel2-2.3.10.37.jar) 
    UCHIJA  props{2.0.2} [Decocraft](Decocraft-2.0.2_1.7.10.jar) 
    UCHIJA  DragonsRadioMod{1.6.3} [Dragon's Radio Mod](DragonsRadioMod-MC1.7.10-1.6.3.jar) 
    UCHIJA  eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJA  ExtraUtilities{1.2.6} [Extra Utilities](extrautilities-1.2.6.jar) 
    UCHIJA  FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJA  fastleafdecay{1.1} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.1.jar) 
    UCHIJA  foxlib{1.7.10-0.7.0} [FoxLib](FoxLib-1.7.10-0.7.0.jar) 
    UCHIJA  GregsLighting{1.11.2} [Greg's Lighting](GregsLighting-1.11.2-mc1.7.10.jar) 
    UCHIJA  gregtech{GT6-MC1710} [GregTech](gregtech_1.7.10-6.00.50.jar) 
    UCHIJA  gtextras{0.3.2} [GTExtras](GTExtras-0.3.2.jar) 
    UCHIJA  ImmibisCore{59.1.1} [Immibis Core](immibis-core-59.1.1.jar) 
    UCHIJA  LavaMonsters{2.2.1} [Lava Monsters](LavaMonsters-1.7.10-2.2.1.jar) 
    UCHIJA  Morpheus{1.7.10-1.6.4} [Morpheus](Morpheus-1.7.10-1.6.4.jar) 
    UCHIJA  NEIAddons{1.12.10.33} [NEI Addons](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  neiintegration{1.0.9} [NEI Integration](NEIIntegration-MC1.7.10-1.0.9.jar) 
    UCHIJA  ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
    UCHIJA  MapWriter{2.1.2} [MapWriter](Opis-1.2.5_1.7.10.jar) 
    UCHIJA  Opis{1.2.5} [Opis](Opis-1.2.5_1.7.10.jar) 
    UCHIJA  psychedelicraft{1.5.2} [Psychedelicraft](Psychedelicraft-1.5.2.n110.jar) 
    UCHIJA  RedLogic{59.1.11} [RedLogic](redlogic-59.1.11.jar) 
    UCHIJA  SpecialMobs{3.1.1} [Special Mobs](SpecialMobs-1.7.10-3.1.1.jar) 
    UCHIJA  Tails{1.7.10-1.3.1} [Tails](Tails-1.7.10-1.3.1.jar) 
    UCHIJA  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.06' Renderer: 'GeForce GT 720/PCIe/SSE2'
    Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GT 720/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.06, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by xarses** [comment]
Same error for me (same server)

**Comment by Blood-Asp** [comment]
A bit better discription about what exactply happens would be nice. Does server and client crash, or only one? Is it only with certain parts in it or while doing something? Does it effect everyone or only certain players?

From what i can see, there is a Bibliocraft armor stand in the stacktrace involved. Did you try to place the armor on it?

**Comment by bear989** [comment]
the arnor is on a biblio armor stand, it didn't crash until the chunk was
reloaded. now anyone entering the area crashes, client only. the full armor
is on the the stand so not sure if it's any certain piece or not.

**Comment by Blood-Asp** [comment]
Seems the armorstand inits the armor differently than a normal player wearing it. But should be easy to fix. Will try to do it once i'm home from work.

**Comment by bear989** [comment]
thanks

**Comment by Blood-Asp** [comment]
Please try if this build works. Should now render fine. In case it is still bugged, is has a try catch and displays a default armor texture (likely broken looking).
https://www.dropbox.com/s/1guk3olzftz6wod/GTExtras-0.3.3.jar?dl=0

**Comment by bear989** [comment]
it works, thanks
